new changes on view project event listener
nwankwo-ikemefuna/js-mini-projects pull request #12
Opened 2022-08-31 11:41 UTC by john-afiukwa

I'm done

2022-08-31 12:30 UTC, nwankwo-ikemefuna requested changes
Looking good so far, just some extra additions and improvements

2022-08-31 12:30 UTC, nwankwo-ikemefuna commented on projects/display-project.js
> +const isView = !queryParams.isView;
What are you doing here?

2022-08-31 12:30 UTC, nwankwo-ikemefuna commented on projects/display-project.js
> +if (isView) {
Should you be doing this check? Isn't this js file for viewing project only?

2022-08-31 12:30 UTC, nwankwo-ikemefuna commented on projects/display-project.js
> +  displayProjectContainer.append(displayTitleHolder, displayContentHolder);
What about the rest of the project data? Department, student, supervisor, etc?

2022-08-31 12:30 UTC, nwankwo-ikemefuna commented on projects/project-common.js
> +        // displayModal(
Remove this commented out code since it's no longer need and won't be

2022-08-31 12:30 UTC, nwankwo-ikemefuna commented on projects/display-projects.html
> +            <!--Render using javascript -->
Create the elements for each project detail in the html and target them in javascript by ID to render their contents.

2022-09-01 10:36 UTC, nwankwo-ikemefuna requested changes
Looks much better, just a few more cleanup changes.

2022-09-01 10:36 UTC, nwankwo-ikemefuna commented on projects/display-project.js
>  let currentlyViewedProjectId = 0;
There's no need for this initialisation to 0. You only do this when you're going to re-assign the variable to a new value inside a new scope (e.g. if/loop/function block), with intention to use the variable after.
For example:
```
let currentlyViewedProjectId = 0;
if (someVariableName === true) {
   currentlyViewedProjectId = 5;
}
console.log(currentlyViewedProjectId); // value will be 5 if someVariableName === true, otherwise it will be 0 (the initial value)
```

Since you're not re-assigning the variable in a scope, just go ahead and assign the current value to it:
`const currentlyViewedProjectId = +queryParams.id;`

2022-09-01 10:36 UTC, nwankwo-ikemefuna commented on projects/display-project.js
> +const studentName = getStudentById(viewedProject.studentId);
This variable has a misleading name. getStudentById function returns an object, unless you pass a second argument to get the value of a property in the object. So you should do one of the following:
```
// 1. passing a second argument to get the student name (returns string)
const studentName = getStudentById(viewedProject.studentId, 'name');

// 2. accessing the name property on the returned object (returns string)
const studentName = getStudentById(viewedProject.studentId).name;

// 3. getting the entire student object (returns object)
// use this approach if you want to obtain more than 1 property of the student object 
const studentObj = getStudentById(viewedProject.studentId);
const studentName = studentObject.name;
```

2022-09-01 10:36 UTC, nwankwo-ikemefuna commented on projects/display-project.js
> +displayStudentHolder.innerHTML = `<b>Name:</b> ${studentName.name}`
If you did one of the following above, then `studentName` will be a string, so you don't need to do `studentName.name` anymore.

2022-09-01 10:36 UTC, nwankwo-ikemefuna commented on projects/project.css
> +.project-display-date-of-submission {
There's no need for each info box to have a separate class. You should give them one class name and the styles will apply to all. Consider `project-info-display-box`

2022-09-02 16:24 UTC, john-afiukwa commented
All issues resolved

2022-09-02 16:24 UTC, closed without merging